### ISSUE TITLE
Status of Meta Module

### ISSUE THREAD

**Issue by splitice** [openresty/meta-lua-nginx-module#56]
What is the status of the meta module in respect to the http module.

A diff between the generated output of the meta module for the http subsystem and the http modules committed files shows many differences. After a few fixes to the meta module (e.g https://github.com/splitice/meta-lua-nginx-module/commit/b4a3d6c1398eed41f249754d75d5b0e6af658503) output it does compile, it does not however pass tests.

Perhaps the README should be extended with some documentation as to the current status?

**Comment by thibaultcha** [comment]
Considering this answered and closing it. FYI, I just opened #70 which lists the missing commits in this repo as of today. There is also https://github.com/openresty/meta-lua-nginx-module/pull/66 which fixes the compilation issues when generating ngx_http_lua from this module. I'll spend some time taking care of it. Thanks!
